services:
  clip-trip-db:
    image: mysql:latest
    platform: linux/x86_64
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cliptrip!
      MYSQL_DATABASE: clip-trip-db
      MYSQL_USER: cliptrip
      MYSQL_PASSWORD: cliptrip!
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
