name: CD - Deploy to Elastic Beanstalk

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      APPLICATION_NAME: clip-trip
      ENVIRONMENT_NAME: Clip-trip-server-env
      DEPLOY_LABEL: github-actions-${{ github.run_number }}
      DOCKER_IMAGE_URI: 118497224929.dkr.ecr.ap-northeast-2.amazonaws.com/clip-trip-server:latest
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      S3_KEY: deploy/docker-run-${{ github.run_number }}.zip

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create Dockerrun.aws.json
        run: |
          cat > Dockerrun.aws.json <<EOF
          {
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "${{ env.DOCKER_IMAGE_URI }}",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": 8080
              }
            ]
          }
          EOF

      - name: Zip Dockerrun.aws.json
        run: zip deploy.zip Dockerrun.aws.json

      - name: Upload to S3
        run: |
          aws s3 cp deploy.zip s3://$S3_BUCKET/$S3_KEY

      - name: Create Application Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name $APPLICATION_NAME \
            --version-label $DEPLOY_LABEL \
            --source-bundle S3Bucket=$S3_BUCKET,S3Key=$S3_KEY \
            --auto-create-application
      
      - name: Wait for application version to be processed
        run: |
          for i in {1..10}; do
            STATUS=$(aws elasticbeanstalk describe-application-versions \
              --application-name $APPLICATION_NAME \
              --version-label $DEPLOY_LABEL \
              --query "ApplicationVersions[0].Status" \
              --output text)

            echo "Current status: $STATUS"

            if [ "$STATUS" = "PROCESSED" ]; then
              echo "Application version processed."
              break
            fi

            echo "Waiting for application version to be processed..."
            sleep 5
          done
      
      - name: Update Environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name $ENVIRONMENT_NAME \
            --version-label $DEPLOY_LABEL
